// data/sponsorshipPackages.ts

export const sponsorshipPackages = [
  {
    id: "banner",
    name: "Banner Sponsor",
    price: 500,
    includedEntries: 0,
    benefits: ["Banner on a hole"],
  },
  {
    id: "hole_1000",
    name: "Hole Sponsor",
    price: 1000,
    includedEntries: 1,
    benefits: ["Banner on a hole", "Entry for a team into ONE Frogman event"],
  },
  {
    id: "event_1500",
    name: "Event Sponsor",
    price: 1500,
    includedEntries: 1,
    benefits: ["Banner on a hole", "Entry for a team into BOTH Frogman events"],
  },
  {
    id: "hole_2500",
    name: "Hole Sponsor (Dinner Table)",
    price: 2500,
    includedEntries: 1,
    dinnerTable: true,
    benefits: [
      "Banner on a hole",
      "Entry for a team into BOTH Frogman events",
      "Table for 10 at benefit dinner",
    ],
  },
  {
    id: "golf_cart",
    name: "Golf Cart Sponsor",
    price: 5000,
    includedEntries: 1,
    sealPlay: true,
    dinnerTable: true,
    benefits: [
      "Logo on every rental cart",
      "Entry for a team into BOTH Frogman events",
      "Play with a SEAL in the Scramble (per request)",
      "Table for 10 at benefit dinner",
    ],
  },
  {
    id: "driving_range",
    name: "Driving Range Sponsor",
    price: 5000,
    includedEntries: 1,
    sealPlay: true,
    dinnerTable: true,
    benefits: [
      "Company logo on 5x20 ft banner",
      "Entry for a team into BOTH Frogman events",
      "Play with a SEAL (per request)",
      "Table for 10 at benefit dinner",
    ],
  },
  {
    id: "tee_block",
    name: "Tee Block Sponsor",
    price: 7500,
    includedEntries: 1,
    sealPlay: true,
    dinnerTable: true,
    benefits: [
      "Company logo on EVERY tee block",
      "Entry for a team into BOTH Frogman events",
      "Play with a SEAL (per request)",
      "Table for 10 at benefit dinner",
    ],
  },
  {
    id: "flag",
    name: "Flag Sponsor",
    price: 7500,
    includedEntries: 1,
    sealPlay: true,
    dinnerTable: true,
    benefits: [
      "Company logo on every flag",
      "Entry for a team into BOTH Frogman events",
      "Play with a SEAL (per request)",
      "Table for 10 at benefit dinner",
    ],
  },
  {
    id: "seal",
    name: "SEAL Sponsor",
    price: 7500,
    includedEntries: 1,
    sealPlay: "both",
    dinnerTable: true,
    benefits: [
      "3x5 ft banner on clubhouse",
      "Entry for a team into BOTH Frogman events",
      "Play with a SEAL for BOTH events (3 days)",
      "Table for 10 at benefit dinner",
    ],
  },
  {
    id: "tee_prize",
    name: "Tee Prize Sponsor",
    price: 10000,
    includedEntries: 1,
    dinnerTable: true,
    benefits: [
      "Logo on tee prize swag bags",
      "Company logo on ProV1 balls",
      "Entry for a team into BOTH Frogman events",
      "Table for 10 at benefit dinner",
    ],
  },
  {
    id: "tournament",
    name: "Tournament Sponsor",
    price: 20000,
    includedEntries: 5,
    dinnerTables: 1,
    benefits: [
      "Event named after your company",
      "(5) Entries into Frogman events",
      "Company logo on every scorecard",
      "Table for 10 at benefit dinner",
      "Special tee prize with company logo",
    ],
  },
];
